### ISSUE TITLE
numbering goes from 0-511 instead of 1-512

### ISSUE THREAD

**Issue by wugmump** [wiedi/node-dmx#49]
Shouldn't it be the other way?

**Comment by bluemaex** [comment]
@wugmump this has been changed quite a while because many people have asked this question, see https://github.com/wiedi/node-dmx/commit/00d960e441024627e1023e2ac0776b899ed6b9af and  the related issue https://github.com/wiedi/node-dmx/issues/39

Which version are you using and where do you get it from? Or maybe I misunderstood the question :)
